### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yil8**
Gene expression inference with deep learning: bioRxiv -> Bioinformaitcs

### CODE REVIEW

**Comment by gokceneraslan** [comment]
Thanks a lot! Do you mind updating the link to DOI?

**Comment by yil8** [comment]
No problem. But I've tried the current DOI (10.1093/bioinformatics/btw074), it does not seem to work yet.

**Comment by yil8** [comment]
The DOI link seems to work now.

**Comment by gokceneraslan** [comment]
Updated, thanks.

**Comment by yil8** [comment]
Thanks so much!

**Pull request closed without merging**
