### PR TITLE
FIDDLE article is added

### PR DESCRIPTION
**Pull request by skyfallen**
I have added a recent (Oct 2016) article on genomic data integration framework using Deep Learning.

### CODE REVIEW

**Comment by gokceneraslan** [comment]
Great, thanks. Can you also add `L. Stirling Churchman` as author?

**Comment by skyfallen** [comment]
Yes, sure, sorry I thought that only the first author is mentioned.

**Comment by skyfallen** [comment]
Done.

**Comment by gokceneraslan** [comment]
Thanks!

**Pull request merged**
