### PR TITLE
added 2016 MSB review from Oliver Stegle

### PR DESCRIPTION
**Pull request by Avsecz**

### CODE REVIEW

**Comment by cgreene** [comment]
:+1: looks good to me

**Comment by alxndrkalinin** [comment]
For the consistency, link should be via DOI, i.e. http://doi.org/10.15252/msb.20156651

**Comment by gokceneraslan** [comment]
Thanks a lot! DOI links are highly appreciated, though.

**Comment by Avsecz** [comment]
:+1: Added the doi link.

**Pull request merged**
